spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/ms_email?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 50
    max-idle: 20
    min-idle: 10
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ********@*****
    password: **************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

